FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY train.py ./
COPY src ./src
COPY config ./config
COPY dvc.yaml ./
COPY orchestration ./orchestration
COPY scripts ./scripts

CMD ["python", "train.py"]
