name: Deploy

on:
  workflow_call:
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      TF_ARTIFACTS_BUCKET:
        required: true
      AWS_ROLE_ARN:
        required: true
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_artifacts_bucket_name: ${{ secrets.TF_ARTIFACTS_BUCKET }}
  MLFLOW_IMAGE: ghcr.io/mlflow/mlflow:v2.11.3

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        run: |
          docker build -t cfd-api -f Dockerfile.api .
          docker tag cfd-api:latest "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}://{{ github.sha }}"
          docker push "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}://{{ github.sha }}"

      - name: Build and push training image
        run: |
          docker build -t cfd-train -f Dockerfile.train .
          docker tag cfd-train:latest "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}://{{ github.sha }}"
          docker push "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}://{{ github.sha }}"

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
      
      - name: Terraform apply
        working-directory: terraform
        env:
          TF_VAR_api_image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}://{{ github.sha }}
          TF_VAR_mlflow_image: ${{ env.MLFLOW_IMAGE }}
        run: |
          terraform init
          terraform apply -auto-approve
